---
title: "REFERENCIAS"
editor: visual
---
Méndez, J. P., García, F. P., & Cervantes, N. H. (2011). Métodos comparativos del poder germinativo en Hordeum distichon  L. calidad maltera.
Mercado, S. A. S., Bayona, H. A. M., & Caleño, J. D. Q. (2018). Evaluación de la calidad fisiológica de las semillas de Linum usitatissimumL. con la prueba de tetrazolio. Avances en Investigación Agropecuaria, 22(3), 46-56.
Palacio, S. A., & Agudelo, B. (2020). Desarrollo del girasol (Helianthus annuus L.) con aplicación de codornaza bajo distintas láminas de riego. Ciencia y Agricultura, 17(1), 3-17.
Rosasco, I. (2017). Estudio de la Calidad Fisiológica de Semillas de Girasol (Helianthus annuus L.) Durante su Procesamiento: Un caso particular. https://rephip.unr.edu.ar/server/api/core/bitstreams/3b002581-03d2-465d-9502-d983fd593f96/content
Salazar, A. (2018). Viabilidad de semillas de  Glycine max  (l.) Utilizando la prueba de tetrazolio. ResearchGate. https://www.researchgate.net/publication/326927376_Viabilidad_de_semillas_de_Glycine_max_l_Utilizando_la_prueba_de_tetrazolio
Valdivia, C. B., Figueroa, C. E., & Flores Pimentel, M. (2018). Prueba de tetrazolio en semillas de espárrago (Asparagus officinalis L.). Anales Científicos, 79(2), 386. https://doi.org/10.21704/ac.v79i2.894
